name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # twice a day
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=%2310b981&color_dots=%230b1f17,%23134e33,%230f9d63,%2334d399,%236ee7b7
            dist/github-snake-dark.svg?color_snake=%2310b981&color_dots=%2307120d,%23134e33,%230f9d63,%2334d399,%236ee7b7

      - name: Push snake to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
